export const FETCH_ROOM_TYPES_REQUEST = 'FETCH_ROOM_TYPES_REQUEST';
export const FETCH_ROOM_TYPES_SUCCESS = 'FETCH_ROOM_TYPES_SUCCESS';
export const FETCH_ROOM_TYPES_FAIL = 'FETCH_ROOM_TYPES_FAIL';
export const DELETE_ROOM_TYPE = 'DELETE_ROOM_TYPE';

